module.exports = {
  // The name of an SSM parameter used to store the private key of the certifcate associated with the AWS integration connected app.
  privateKeyParamName: process.env.PRIVATE_KEY_PARAM_NAME,
  // The name of an SSM parameter used to store the consumer key of the AWS integration connected app.
  consumerKeyParamName: process.env.CONSUMER_KEY_PARAM_NAME,
  // The name of an SSM parameter used ot store the access token generated by the connected app
  accessTokenParamName: process.env.ACCESS_TOKEN_PARAM_NAME,
  // The audience specified in the claim of the generated JWT token.
  audienceParamName: process.env.AUDIENCE,
  // The subject specified in the claim of the generated JWT token.
  subjectParamName: process.env.SUBJECT,
  // JWT token valid duration
  tokenValidFor: "3m",
  salesforceAuthEndpoint: process.env.SALESFORCE_AUTH_ENDPOINT,
  salesforceRestApiEndpointBase: process.env.SALESFORCE_REST_API_ENDPOINT_BASE,
  callCenterApiName: process.env.CALL_CENTER_API_NAME,
};
