---
Description: |
  Service Voice Tenant Provisioning Stage CloudFormation
Parameters:
  Sku:
    Type: String
    Description: SkU Type of the contact center
    AllowedValues:
      - RESELL
      - BYOA
Conditions:
  UseResellCondition:
    !Equals [ !Ref Sku, RESELL]

Resources:
  SSMManagedPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:*
            Resource:
              - !Join ["",[!Sub 'arn:${AWS::Partition}:ssm:*:${AWS::AccountId}:parameter/','*-salesforce-*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:ssm:*:${AWS::AccountId}:parameter/','*-scrt-jwt-auth-private-key']]
      Description: Policy to access Salesforce defined ssm
      ManagedPolicyName: !If [UseResellCondition, "SSMAccessPolicy", !Sub "SCVSSMAccessPolicy"]
      Path: /scv/
  LambdaManagedPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
              - lambda:InvokeAsync
              - lambda:ListFunctions
              - lambda:AddPermission
              - lambda:RemovePermission
            Resource:
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*VoiceMailTranscribeFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*ContactLensProcessorFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*kvsTranscriber*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*RealtimeAlert*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*kvsConsumerTrigger*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*InvokeTelephonyIntegrationApiFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*ContactLensProcessorFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*ContactLensConsumerFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*CTRDataSyncFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*InvokeSalesforceRestApiFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*AuthKeysSSMUtilFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*HandleContactEventsFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*CustomSSMFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*RealtimeAlert*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*ConnectConfigurationFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*S3BucketPolicyConfigurationFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*SCVAccessBYOACConfigurationFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*S3BucketEventBridgeConfigurationFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*TDGConfigurationFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*VoiceMailAudioProcessingFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*VoiceMailTranscribeFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*VoiceMailPackagingFunction*']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:','*ContactDataSyncFunction*']]
      Description: Policy to access Salesforce owned lambda functions
      ManagedPolicyName: !If [UseResellCondition, "LambdaAccessPolicy", !Sub "SCVLambdaAccessPolicy"]
      Path: /scv/
  KMSManagedPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - kms:CreateGrant
              - kms:DescribeKey
              - kms:ListAliases
              - kms:RetireGrant
            Resource: "*"
            Condition:
              StringLike:
                "kms:RequestAlias":
                 - "alias/aws/kinesisvideo"
                 - "alias/aws/lambda"
                 - "alias/aws/ssm"
          - Effect: Allow
            Action:
              - kms:CreateGrant
              - kms:DescribeKey
              - kms:ListAliases
              - kms:RetireGrant
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/resourceOwner": "scv"
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: "*"
      Description: Policy to access Salesforce owned Keys
      ManagedPolicyName: !If [UseResellCondition, "KMSAccessPolicy", !Sub "SCVKMSAccessPolicy"]
      Path: /scv/
  KinesisDataStreamManagedPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - kinesis:DescribeStream
              - kinesis:DescribeStreamSummary
              - kinesis:GetRecords
              - kinesis:GetShardIterator
              - kinesis:ListShards
              - kinesis:ListStreams
              - kinesis:SubscribeToShard
            Resource:
              - !Join ["",[!Sub 'arn:${AWS::Partition}:kinesis:*:${AWS::AccountId}:stream/','*-CTRStream']]
              - !Join ["",[!Sub 'arn:${AWS::Partition}:kinesis:*:${AWS::AccountId}:stream/','*-ContactLensStream']]
          - Effect: Allow
            Action:
              - kinesis:PutRecord
              - kinesis:PutRecords
            Resource:
              - !Join [ "",[ !Sub 'arn:${AWS::Partition}:kinesis:*:${AWS::AccountId}:stream/','*-CTRStream' ] ]
              - !Join [ "",[ !Sub 'arn:${AWS::Partition}:kinesis:*:${AWS::AccountId}:stream/','*-ContactLensStream' ] ]
      Description: Policy to access Salesforce owned kinesis datastreams
      ManagedPolicyName: !If [UseResellCondition, "KinesisDataStreamAccessPolicy", !Sub "SCVKinesisDataStreamAccessPolicy"]
      Path: /scv/
  S3ManagedPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:List*
              - s3:Get*
              - s3:PutObject
              - s3:PutObjectTagging
            Resource: "*"
            Condition:
              StringEquals:
                "aws:ResourceTag/resourceOwner": "scv"
      Description: Policy to access s3 bucket created and managed by salesforce
      ManagedPolicyName: !If [UseResellCondition, "S3AccessPolicy", !Sub "SCVS3AccessPolicy"]
      Path: /scv/
  AmazonConnectManagedPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - connect:Get*
              - connect:List*
              - connect:Search*
              - connect:Describe*
              - connect:AssociateApprovedOrigin
              - connect:AssociateInstanceStorageConfig
              - connect:AssociateLambdaFunction
              - connect:AssociatePhoneNumberContactFlow
              - connect:AssociateQueueQuickConnects
              - connect:AssociateRoutingProfileQueues
              - connect:AssociateTrafficDistributionGroupUser
              - connect:CreateAgentStatus
              - connect:CreateContactFlow
              - connect:CreateInstance
              - connect:CreateHoursOfOperation
              - connect:CreateContactFlowModule
              - connect:CreateQueue
              - connect:CreateQuickConnect
              - connect:CreateRoutingProfile
              - connect:CreateTrafficDistributionGroup
              - connect:CreateUser
              - connect:ReplicateInstance
              - connect:StartOutboundVoiceContact
              - connect:TagResource
              - connect:UpdateTrafficDistribution
              - connect:UpdateQuickConnectName
              - connect:UpdateInstanceAttribute
              - connect:UpdateHoursOfOperation
              - connect:UpdateQueueName
              - connect:UpdateQueueStatus
              - connect:DeleteQueue
              - connect:DeleteUser
              - connect:DeleteQuickConnect
              - connect:DisassociateLambdaFunction
              - connect:DisassociateApprovedOrigin
              - connect:DisassociateQueueQuickConnects
              - connect:DisassociateTrafficDistributionGroupUser
              - connect:DisassociateRoutingProfileQueues
              - connect:MonitorContact
              - connect:UpdateUserRoutingProfile
              - connect:UpdateContactAttributes
              - connect:UpdateRoutingProfileQueues
              - connect:UpdateRoutingProfileName
              - connect:UpdateRoutingProfileDefaultOutboundQueue
              - connect:UpdateContactRoutingData
              - connect:PutUserStatus
              - connect:UpdateQueueHoursOfOperation
              - connect:ClaimPhoneNumber
              - connect:AssociatePhoneNumberContactFlow
              - connect:DisassociatePhoneNumberContactFlow
              - connect:ReleasePhoneNumber
              - connect:ListPhoneNumbersV2
              - connect:UpdateQueueOutboundCallerConfig
            Resource: "*"
      Description: Policy to access Salesforce owned Keys
      ManagedPolicyName: !If [UseResellCondition, "AmazonConnectAccessPolicy", !Sub "SCVAmazonConnectAccessPolicy"]
      Path: /scv/

Outputs:
  SSMManagedPolicyResource:
    Description: Implicit IAM Role created for CTRDataSyncFunction
    Value: !Ref SSMManagedPolicyResource
  LambdaManagedPolicyResource:
      Description: Policy to access Salesforce owned lambda functions
      Value: !Ref LambdaManagedPolicyResource
  KMSManagedPolicyResource:
    Description: Policy to access Salesforce owned parameter store
    Value: !Ref KMSManagedPolicyResource
  KinesisDataStreamManagedPolicyResource:
    Description: Implicit IAM Role created for CTRDataSyncFunction
    Value: !Ref KinesisDataStreamManagedPolicyResource
  S3ManagedPolicyResource:
    Description: Policy to access Salesforce owned Keys
    Value: !Ref S3ManagedPolicyResource
  AmazonConnectManagedPolicyResource:
    Description: Policy to access integrated Connect Instance with Salesforce
    Value: !Ref AmazonConnectManagedPolicyResource

